[alias]
today = "run  --release --features today -- today"
scaffold = "run  --release -- scaffold"
download = "run  --release -- download"
read = "run  --release -- read"

solve = "run  --release -- solve"
all = "run  --release -- all"
time = "run  --release -- time"

[env]
AOC_YEAR = "2023"
